# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projet.ui',
# licensing of 'projet.ui' applies.
#
# Created: Fri Jul 26 15:41:00 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1249, 831)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 971, 581))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 0, 160, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cbEtablissement = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbEtablissement.setObjectName("cbEtablissement")
        self.gridLayout.addWidget(self.cbEtablissement, 1, 1, 1, 1)
        self.lAcademie = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lAcademie.setObjectName("lAcademie")
        self.gridLayout.addWidget(self.lAcademie, 0, 0, 1, 1)
        self.lEtablissement = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lEtablissement.setObjectName("lEtablissement")
        self.gridLayout.addWidget(self.lEtablissement, 1, 0, 1, 1)
        self.cbAcademie = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbAcademie.setObjectName("cbAcademie")
        self.gridLayout.addWidget(self.cbAcademie, 0, 1, 1, 1)
        self.lClasse = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lClasse.setObjectName("lClasse")
        self.gridLayout.addWidget(self.lClasse, 2, 0, 1, 1)
        self.cbClasse = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbClasse.setObjectName("cbClasse")
        self.gridLayout.addWidget(self.cbClasse, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pbAjouterAcademie = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbAjouterAcademie.setObjectName("pbAjouterAcademie")
        self.verticalLayout.addWidget(self.pbAjouterAcademie)
        self.pbAjouterEtablissement = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbAjouterEtablissement.setObjectName("pbAjouterEtablissement")
        self.verticalLayout.addWidget(self.pbAjouterEtablissement)
        self.pbAjouterClasse = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbAjouterClasse.setObjectName("pbAjouterClasse")
        self.verticalLayout.addWidget(self.pbAjouterClasse)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(230, 20, 641, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.twTableau = QtWidgets.QTableWidget(self.tab)
        self.twTableau.setGeometry(QtCore.QRect(300, 31, 321, 391))
        self.twTableau.setColumnCount(2)
        self.twTableau.setObjectName("twTableau")
        self.twTableau.setColumnCount(2)
        self.twTableau.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twTableau.setHorizontalHeaderItem(1, item)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 0, 160, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lCoef = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lCoef.setObjectName("lCoef")
        self.gridLayout_2.addWidget(self.lCoef, 1, 0, 1, 1)
        self.lMatiere = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lMatiere.setObjectName("lMatiere")
        self.gridLayout_2.addWidget(self.lMatiere, 0, 0, 1, 1)
        self.cbMatiere = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMatiere.sizePolicy().hasHeightForWidth())
        self.cbMatiere.setSizePolicy(sizePolicy)
        self.cbMatiere.setObjectName("cbMatiere")
        self.gridLayout_2.addWidget(self.cbMatiere, 0, 1, 1, 1)
        self.dsbCoef = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.dsbCoef.setMaximum(2.0)
        self.dsbCoef.setSingleStep(0.25)
        self.dsbCoef.setObjectName("dsbCoef")
        self.gridLayout_2.addWidget(self.dsbCoef, 1, 1, 1, 1)
        self.lNote = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lNote.setObjectName("lNote")
        self.gridLayout_2.addWidget(self.lNote, 2, 0, 1, 1)
        self.leNote = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leNote.sizePolicy().hasHeightForWidth())
        self.leNote.setSizePolicy(sizePolicy)
        self.leNote.setObjectName("leNote")
        self.gridLayout_2.addWidget(self.leNote, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pbAjouterNote = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pbAjouterNote.setObjectName("pbAjouterNote")

        self.verticalLayout_2.addWidget(self.pbAjouterNote)
        self.tabWidget.addTab(self.tab, "")
        self.Moyenne = QtWidgets.QWidget()
        self.Moyenne.setObjectName("Moyenne")
        self.lGraph = QtWidgets.QLabel(self.Moyenne)
        self.lGraph.setGeometry(QtCore.QRect(-310, 230, 951, 599))
        self.lGraph.setObjectName("lGraph")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Moyenne)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 551, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lListeDesEleves = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lListeDesEleves.setObjectName("lListeDesEleves")
        self.verticalLayout_3.addWidget(self.lListeDesEleves)
        self.lwListe = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwListe.sizePolicy().hasHeightForWidth())
        self.lwListe.setSizePolicy(sizePolicy)
        self.lwListe.setObjectName("lwListe")
        self.verticalLayout_3.addWidget(self.lwListe)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.lGraph_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lGraph_2.setObjectName("lGraph_2")
        self.horizontalLayout.addWidget(self.lGraph_2)
        self.tabWidget.addTab(self.Moyenne, "")
        self.horizontalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1249, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lAcademie.setText(QtWidgets.QApplication.translate("MainWindow", "Academie", None, -1))
        self.lEtablissement.setText(QtWidgets.QApplication.translate("MainWindow", "Etablissement", None, -1))
        self.lClasse.setText(QtWidgets.QApplication.translate("MainWindow", "Classe", None, -1))
        self.pbAjouterAcademie.setText(QtWidgets.QApplication.translate("MainWindow", "Ajouter Academie", None, -1))
        self.pbAjouterEtablissement.setText(QtWidgets.QApplication.translate("MainWindow", "Ajouter Etablissement", None, -1))
        self.pbAjouterClasse.setText(QtWidgets.QApplication.translate("MainWindow", "Ajouter Classe", None, -1))
        self.twTableau.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(8).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.verticalHeaderItem(9).setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle ligne", None, -1))
        self.twTableau.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Nom d\'elève", None, -1))
        self.twTableau.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Note", None, -1))
        self.lCoef.setText(QtWidgets.QApplication.translate("MainWindow", "Coef", None, -1))
        self.lMatiere.setText(QtWidgets.QApplication.translate("MainWindow", "Matiere", None, -1))
        self.lNote.setText(QtWidgets.QApplication.translate("MainWindow", "Epreuve", None, -1))
        self.pbAjouterNote.setText(QtWidgets.QApplication.translate("MainWindow", "Ajouter Note", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Saisie", None, -1))
        self.lGraph.setText(QtWidgets.QApplication.translate("MainWindow", "SetPixtmap = pour mettre un graph", None, -1))
        self.lListeDesEleves.setText(QtWidgets.QApplication.translate("MainWindow", "Liste des eleves", None, -1))
        self.lGraph_2.setText(QtWidgets.QApplication.translate("MainWindow", "SetPixtmap = pour mettre un graph", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Moyenne), QtWidgets.QApplication.translate("MainWindow", "Moyenne", None, -1))

